FROM openresty/openresty:alpine


RUN apk add --no-cache \
    build-base \
    openssl-dev \
    lua5.1-dev \
    git \
    curl \
    luarocks5.1

RUN luarocks-5.1 install ansicolors && \
    luarocks-5.1 install argparse && \
    luarocks-5.1 install date && \
    luarocks-5.1 install etlua && \
    luarocks-5.1 install loadkit && \
    luarocks-5.1 install lpeg && \
    luarocks-5.1 install lua-cjson && \
    luarocks-5.1 install luaossl && \
    luarocks-5.1 install luasocket && \
    luarocks-5.1 install pgmoon && \
    luarocks-5.1 install lapis

RUN luarocks-5.1 install lapis


WORKDIR /app

COPY . .

EXPOSE 8080

CMD ["/usr/local/bin/lapis", "server"]
